[project]
name = "smartsip"
version = "0.1.0"
description = "Aplikacja do monitorowania poziomu nawodnienia"
readme = "README.md"
authors = [
    { name = "Damwid99", email = "damwid@hotmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "sqlmodel>=0.0.22",
    "pydantic-settings>=2.5.2",
    "alembic>=1.13.3",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.15.1",
]

# (Naprawiony warning) Nowy standard uv dla pakietów deweloperskich
[dependency-groups]
dev = [
    "mypy>=1.11.2",
    "ruff>=0.6.9",
    "pytest>=8.3.3",
    "httpx>=0.28.1",
]

# (Naprawiony błąd build) Mówimy uv, że to aplikacja końcowa, a nie biblioteka.
[tool.uv]
package = false

# --- Konfiguracja RUFF (Linter i Formatter) ---
[tool.ruff]
line-length = 100
target-version = "py314"

[tool.ruff.lint]
select = [
    "E",   # standardowe błędy
    "F",   # nieużywane zmienne/importy
    "I",   # automatyczne sortowanie importów (isort)
    "UP",  # podpowiedzi upgrade'u do nowszej składni Pythona
]
ignore = [
    "UP037",
]

# --- Konfiguracja MYPY (Sprawdzanie typów) ---
[tool.mypy]
strict = true
python_version = "3.14"
ignore_missing_imports = true
explicit_package_bases = true
exclude = ["alembic"]

[tool.ruff.lint.per-file-ignores]
"alembic/env.py" = ["I001", "F401"]
"alembic/versions/*" = ["ALL"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]