"""switch to google sso

Revision ID: 86940748b13a
Revises: ab33b9c66239
Create Date: 2026-10-06 08:25:03.916534
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "86940748b13a"
down_revision: Union[str, None] = "ab33b9c66239"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.create_index(batch_op.f("ix_users_google_id"), ["google_id"], unique=True)
        batch_op.drop_column("hashed_password")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hashed_password", sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_users_google_id"))
        batch_op.drop_column("google_id")

    # ### end Alembic commands ###
